# environment.yml

name: dsml
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - aom=3.6.0=h313beb8_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - atk-1.0=2.38.0=hcb7b3dd_1
  - attrs=25.4.0=py311hca03da5_0
  - blas=1.0=openblas
  - bottleneck=1.4.2=py311hb9f6ed7_0
  - brotlicffi=1.0.9.2=py311h313beb8_1
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h191e429_0
  - certifi=2025.10.5=py311hca03da5_0
  - cffi=2.0.0=py311h3a083c1_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.1=py311h48ca7d4_0
  - cpuonly=2.0=0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h80987f9_0
  - debugpy=1.8.16=py311h0962b89_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h313beb8_0
  - filelock=3.17.0=py311hca03da5_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h29935d0_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.1=py311h254cc4a_0
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - gdk-pixbuf=2.42.10=h969f7ef_2
  - gettext=0.21.0=hbdbcc25_2
  - giflib=5.2.2=h93a5062_0
  - glib=2.84.2=hc880cf1_0
  - glib-tools=2.84.2=hc880cf1_0
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.1=py311h5c1b81f_0
  - graphite2=1.3.14=hc377ac9_1
  - graphviz=9.0.0=h3face73_1
  - gtk2=2.24.33=h57013de_2
  - gts=0.7.6=he42f4ea_4
  - harfbuzz=10.2.0=he637ebf_1
  - icu=73.1=h313beb8_0
  - idna=3.7=py311hca03da5_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh92f572d_0
  - ipympl=0.9.8=pyhcf101f3_0
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py311hca03da5_0
  - joblib=1.5.2=py311hca03da5_0
  - jpeg=9f=h2f69dba_0
  - jsonschema=4.25.0=py311hca03da5_0
  - jsonschema-specifications=2023.7.1=py311hca03da5_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - kiwisolver=1.4.8=py311h313beb8_0
  - krb5=1.21.3=h237132a_0
  - lcms2=2.16=he26ebf3_1
  - lerc=4.0.0=h313beb8_0
  - libavif=1.1.1=h80987f9_0
  - libcxx=20.1.8=h8869778_0
  - libdeflate=1.22=h80987f9_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.4=hca03da5_1
  - libgd=2.3.3=hd3b0a14_4
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.84.2=hdc2269c_0
  - libiconv=1.16=h80987f9_3
  - libjpeg-turbo=2.0.0=h1a28f6b_0
  - libopenblas=0.3.30=hf2bb037_0
  - libpng=1.6.39=h80987f9_0
  - librsvg=2.58.0=hb3d354b_1
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.50.4=hf8de324_0
  - libtiff=4.7.0=h91aec0a_0
  - libwebp=1.3.2=hf40cdb4_1
  - libwebp-base=1.3.2=h80987f9_1
  - libxml2=2.13.8=h0b34f26_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=3.0.2=py311h80987f9_0
  - matplotlib=3.10.6=py311hca03da5_0
  - matplotlib-base=3.10.6=py311h066045a_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py311hca03da5_0
  - narwhals=2.10.0=pyhcf101f3_0
  - nbformat=5.10.4=py311hca03da5_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=py311hca03da5_0
  - numexpr=2.11.0=py311h8c72970_1
  - openjpeg=2.5.2=hba36e21_1
  - openssl=3.5.4=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311hc6ded6b_0
  - pango=1.50.14=hcf40dda_2
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.42=hb066dcc_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py311h6dd570d_0
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h09dc60e_0
  - platformdirs=4.4.0=pyhcf101f3_0
  - plotly=6.3.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.0.0=py311h254cc4a_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.23=py311hca03da5_0
  - pydot=4.0.1=py311h267d04e_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.0=py311hca03da5_0
  - pysocks=1.7.1=py311hca03da5_0
  - python=3.11.11=h89a136b_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.20.0=py311hca03da5_0
  - python-graphviz=0.21=pyhbacfb6d_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.11=8_cp311
  - pytorch=2.2.2=py3.11_0
  - pytorch-mutex=1.0=cpu
  - pytz=2025.2=py311hca03da5_0
  - pyyaml=6.0.2=py311h80987f9_0
  - pyzmq=27.1.0=py311h854a7ef_0
  - readline=8.3=h0b18652_0
  - referencing=0.30.2=py311hca03da5_0
  - requests=2.32.5=py311hca03da5_0
  - rpds-py=0.22.3=py311h2aea54e_0
  - scikit-learn=1.7.2=py311hc6ded6b_0
  - scipy=1.16.2=py311h53ebd84_0
  - setuptools=78.1.1=py311hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=h79febb2_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.14.0=py311hca03da5_0
  - threadpoolctl=3.5.0=py311hb6e6a13_0
  - tk=8.6.15=hcd8a7d5_0
  - torchaudio=2.2.2=py311_cpu
  - torchvision=0.17.2=py311_cpu
  - tornado=6.5.1=py311h80987f9_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py311hca03da5_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py311hca03da5_0
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - accelerate==1.11.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - easyocr==1.7.2
      - fsspec==2025.9.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - imageio==2.37.2
      - kagglehub==0.3.13
      - lazy-loader==0.4
      - ninja==1.13.0
      - numpy==2.2.6
      - ollama==0.6.0
      - opencv-python-headless==4.12.0.88
      - pyclipper==1.3.0.post6
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - python-bidi==0.6.7
      - regex==2025.11.3
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - shapely==2.1.2
      - sniffio==1.3.1
      - tifffile==2025.10.16
      - tokenizers==0.22.1
      - tqdm==4.67.1
      - transformers==4.57.1
      - typing-inspection==0.4.2
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/dsml
